version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    environment:
      - discovery.type=single-node
      - network.host=0.0.0.0
      - xpack.security.enabled=false
    ports:
      - 9200:9200

  python:
    build:
      context: .
    volumes:
      - ./:/usr/src/app
    depends_on:
      - elasticsearch
    stdin_open: true
    tty: true